### PR TITLE
Solving issue #5 "use this keyword on the constructor"

### PR DESCRIPTION
**Pull request by AlbertoYabeda**
hi @priyankapiba  again.
Solved this issue.
already tested the game with the new changes, but u can do test it again.
thanks.

### CODE REVIEW

**Comment by priyankapiba** [comment]
Well Done!
All the best for the future! :)

**Comment by AlbertoYabeda** [comment]
thank you @priyankapiba 
can u pls add the accepted lable pls?

wish you all the best too.👌

**Comment by priyankapiba** [comment]
I have already added hacktoberfest-accepted label.

**Comment by AlbertoYabeda** [comment]
ohh sorry. 
I hadn't seen it before.
thankiu very much
I learned a lot about contributing to open source project in this project👍👌
i'm going to work on the choosing player emoji later 

good luck and stay safe.

**Comment by priyankapiba** [comment]
No worries!
Happy to hear this.
We at GDSC MESCOE conduct various technical events and hackathons.
You can join our discord server here: [https://discord.gg/HcKV46cQ](URL)

**Comment by AlbertoYabeda** [comment]
I get an 404 error on this link. I wanna join and see what's happining in there

**Pull request merged**
